import React, { createContext, useContext, useEffect, useMemo, useRef, useState } from "react";

import { useOptionalAuth } from "@/contexts/AuthContext";
import { loadProfilePreferences, persistProfilePreferences } from "@/lib/profilePreferences";
import { safeStorageGetItem, safeStorageSetItem } from "@/lib/safeStorage";

export type AppLanguage = "en" | "bn";

type TranslationKey = keyof typeof translations.en;

type TranslationValues = Record<string, string | number>;

type LanguageContextType = {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => void;
  t: (key: TranslationKey, values?: TranslationValues) => string;
};

const LANGUAGE_STORAGE_KEY = "settings-language";

const translations = {
  en: {
    "nav.home": "Home",
    "nav.search": "Search",
    "nav.browse": "Browse",
    "nav.unreleased": "Unreleased",
    "nav.library": "Library",
    "nav.profile": "Profile",
    "nav.notifications": "Notifications",
    "nav.history": "History",
    "nav.settings": "Settings",

    "sidebar.searchPlaceholder": "Search...",
    "sidebar.searchLibraryPlaceholder": "Search Library...",
    "sidebar.loadingSearch": "Loading search...",
    "sidebar.yourLibrary": "Your Library",
    "sidebar.playlists": "Playlists",
    "sidebar.albums": "Albums",
    "sidebar.artists": "Artists",
    "sidebar.recents": "Recents",
    "sidebar.alphabetical": "Alphabetical",
    "sidebar.noMatchesFound": "No matches found",
    "sidebar.createPlaylist": "Create",
    "sidebar.newPlaylist": "New Playlist",
    "sidebar.playlistNamePlaceholder": "Playlist name",
    "sidebar.playlistCreated": "Created \"{{name}}\"",
    "sidebar.playlistCreateFailed": "Failed to create playlist",
    "sidebar.deletePlaylistConfirm": "Delete \"{{name}}\"? This cannot be undone.",
    "sidebar.playlistDeleted": "Playlist deleted",
    "sidebar.likedSongs": "Liked Songs",
    "sidebar.localFiles": "Local Files",
    "sidebar.localFilesMeta": "On this device · {{count}} tracks",
    "sidebar.playlistMeta": "Playlist · {{count}} songs",
    "sidebar.artist": "Artist",

    "settings.title": "Settings",
    "settings.searchAria": "Search settings",
    "settings.searchPlaceholder": "Search settings",
    "settings.searchNoResults": "No settings matched your search.",
    "settings.account": "Account",
    "settings.language": "Language",
    "settings.audioQuality": "Audio quality",
    "settings.yourLibrary": "Your Library",
    "settings.display": "Display",
    "settings.social": "Social",
    "settings.playback": "Playback",
    "settings.storage": "Storage",
    "settings.guest": "Guest",
    "settings.connectedAccount": "Connected account",
    "settings.signInManage": "Sign in to manage account settings",
    "settings.edit": "Edit",
    "settings.signIn": "Sign in",
    "settings.signOut": "Sign out",
    "settings.signOutDescription": "End session on this device",
    "settings.chooseLanguage": "Choose language",
    "settings.languageDescription": "Changes are applied immediately across the app chrome.",
    "settings.languageEnglish": "English",
    "settings.languageBangla": "Bangla",
    "settings.streamingQuality": "Streaming quality",
    "settings.downloadFormat": "Download format",
    "settings.autoAdjustQuality": "Auto-adjust quality",
    "settings.recommendedOn": "Recommended: On",
    "settings.equalizerDescription": "Enable playback EQ. Reset clears your current EQ curve.",
    "settings.preservePitch": "Preserve pitch",
    "settings.preservePitchDescription": "Keep the original vocal pitch when playback speed changes.",
    "settings.volumeNormalization": "Volume normalization",
    "settings.volumeNormalizationDescription": "Normalize track volume for more consistent playback levels.",
    "settings.compactLibrary": "Use compact library layout",
    "settings.showLocalFiles": "Show local files",
    "settings.showLocalFilesDescription": "Keep an importable Local Files section in your library sidebar and collection pages.",
    "settings.openLocalFiles": "Open local files",
    "settings.localFilesCount": "Local files: {{count}}",
    "settings.localFilesStorage": "Stored locally: {{size}}",
    "settings.offlineApp": "Offline app shell",
    "settings.offlineAppReady": "Core pages are cached for offline launch on this device.",
    "settings.offlineAppPending": "Offline caching is still being prepared for this device.",
    "settings.desktopAppDescription": "Knobb Desktop is running natively on this device, so it does not rely on the browser offline shell.",
    "settings.installApp": "Install app",
    "settings.installAppDescription": "Add Knobb to your home screen or desktop for a closer native app feel.",
    "settings.installAppDesktopDescription": "Knobb Desktop is already installed and running on this device.",
    "settings.installNow": "Install",
    "settings.installed": "Installed",
    "settings.notAvailable": "Not available",
    "settings.desktopDownloads": "Desktop downloads",
    "settings.desktopDownloadsDescription": "Windows releases ship from the desktop repo and auto-update from tagged GitHub releases. Signed macOS publishing is currently on hold pending Apple Developer enrollment.",
    "settings.desktopMainApp": "Knobb Desktop",
    "settings.desktopMainAppDescription": "The full desktop app with tray support and native Discord presence. Windows releases are live; macOS packaging is local-only until Apple signing is available.",
    "settings.desktopCompanionApp": "Knobb Discord Companion",
    "settings.desktopCompanionDescription": "A lighter bridge-only helper. Windows installers ship on the latest release page; signed macOS publishing is currently on hold.",
    "settings.desktopDownloadMac": "Download for macOS",
    "settings.desktopDownloadWindows": "Download for Windows",
    "settings.desktopViewRelease": "View latest release",
    "settings.desktopViewRepo": "Open desktop repo",
    "settings.desktopUpdateVersion": "Current version: {{version}}",
    "settings.desktopUpdatePlatform": "Platform: {{platform}}",
    "settings.desktopCheckUpdates": "Check for updates",
    "settings.desktopRetryUpdate": "Retry update check",
    "settings.desktopRestartUpdate": "Restart to update",
    "settings.dynamicCards": "Dynamic Cards",
    "settings.dynamicCardsDescription": "Controls the hover lift, zoom, and floating action buttons on media cards.",
    "settings.dynamicCardsEnabledOption": "Dynamic",
    "settings.dynamicCardsDisabledOption": "Normal",
    "settings.libraryCardStyle": "Library Item Style",
    "settings.libraryCardStyleDescription": "Switch your library between artwork cards and a compact list layout.",
    "settings.libraryCardStyleCover": "Cover",
    "settings.libraryCardStyleList": "List",
    "settings.rightPanelStyle": "Right sidebar style",
    "settings.rightPanelStyleDescription": "Choose between the plain classic panel and the artwork-driven blurred version.",
    "settings.rightPanelStyleClassic": "Classic",
    "settings.rightPanelStyleArtwork": "Artwork Blur",
    "settings.bottomPlayerStyle": "Bottom player style",
    "settings.bottomPlayerStyleDescription": "Choose between the current tinted player bar and a black version.",
    "settings.bottomPlayerStyleCurrent": "Current",
    "settings.bottomPlayerStyleBlack": "Black",
    "settings.sidebarStyle": "Sidebar style",
    "settings.sidebarStyleDescription": "Switch the library sidebar between a flatter classic treatment and a more atmospheric artwork-inspired shell.",
    "settings.sidebarStyleClassic": "Classic",
    "settings.sidebarStyleArtwork": "Artwork Blur",
    "settings.cardSize": "Card Size",
    "settings.cardSizeDescription": "Smaller cards fit more items in each row.",
    "settings.websiteMode": "Website mode",
    "settings.websiteModeDescription": "Switch the chrome between the current sharp layout and a softer, more fluid roundish look.",
    "settings.websiteModeEdgy": "Edgy",
    "settings.websiteModeRoundish": "Roundish",
    "settings.pageDensity": "Page density",
    "settings.pageDensityDescription": "Choose how tightly the interface packs rows, spacing, and surfaces.",
    "settings.pageDensityComfortable": "Comfortable",
    "settings.pageDensityCompact": "Compact",
    "settings.font": "Font",
    "settings.fontDescription": "Keep Outfit as the default app font or switch the interface to Space Grotesk.",
    "settings.fontDefault": "Default (Outfit)",
    "settings.fontGrotesk": "Space Grotesk",
    "settings.showSidebar": "Show sidebar",
    "settings.showSidebarDescription": "Keep the desktop sidebar visible for navigation and library access.",
    "settings.showScrollbar": "Show scrollbar",
    "settings.showScrollbarDescription": "Display draggable scrollbars inside app panels and sidebars for mouse navigation.",
    "settings.optionYes": "Yes",
    "settings.optionNo": "No",
    "settings.optionShow": "Show",
    "settings.optionHide": "Hide",
    "settings.libraryOpenState": "Library open state",
    "settings.libraryOpenStateDescription": "Choose whether the desktop library sidebar starts expanded or collapsed.",
    "settings.libraryOpenStateExpanded": "Expanded",
    "settings.libraryOpenStateCollapsed": "Collapsed",
    "settings.librarySortDefault": "Library sort default",
    "settings.librarySortDefaultDescription": "Pick the default ordering used when opening your library.",
    "settings.librarySortRecents": "Recents",
    "settings.librarySortAlphabetical": "Alphabetical",
    "settings.coverArtCorners": "Cover art corners",
    "settings.coverArtCornersDescription": "Choose whether cover art stays sharp-edged or rounded across the app.",
    "settings.coverArtCornersSharp": "Sharp",
    "settings.coverArtCornersRounded": "Rounded",
    "settings.accentSource": "Accent source",
    "settings.accentSourceDescription": "Use the playing track artwork for accents, or keep a neutral theme accent everywhere.",
    "settings.accentSourceDynamic": "Dynamic",
    "settings.accentSourceTheme": "Theme",
    "settings.animationMode": "Animations",
    "settings.animationModeDescription": "Use full motion, a reduced version, or turn interface animations off.",
    "settings.animationModeFull": "Full",
    "settings.animationModeReduced": "Reduced",
    "settings.animationModeOff": "Off",
    "settings.blurEffects": "Blur effects",
    "settings.blurEffectsDescription": "Enable or disable the frosted glass and background blur effects used in panels.",
    "settings.rightPanelDefaultTab": "Right panel default tab",
    "settings.rightPanelDefaultTabDescription": "Choose which tab the right panel prefers when it opens automatically.",
    "settings.rightPanelTabQueue": "Queue",
    "settings.rightPanelTabLyrics": "Lyrics",
    "settings.rightPanelAutoOpen": "Auto-open right panel",
    "settings.rightPanelAutoOpenDescription": "Control whether playback automatically opens the right panel.",
    "settings.rightPanelAutoOpenAlways": "Always",
    "settings.rightPanelAutoOpenWhilePlaying": "While Playing",
    "settings.rightPanelAutoOpenNever": "Never",
    "settings.lyricsSyncMode": "Lyrics sync mode",
    "settings.lyricsSyncModeDescription": "Keep lyrics following playback or hold them in a static view.",
    "settings.lyricsSyncModeFollow": "Follow playback",
    "settings.lyricsSyncModeStatic": "Static",
    "settings.playerButtonsLayout": "Player buttons layout",
    "settings.playerButtonsLayoutDescription": "Choose a tighter or more spacious spacing for the bottom player controls.",
    "settings.playerButtonsLayoutCompact": "Compact",
    "settings.playerButtonsLayoutSpacious": "Spacious",
    "settings.trackTitleLines": "Track title lines",
    "settings.trackTitleLinesDescription": "Choose whether player titles stay on one line or can wrap to two lines.",
    "settings.trackTitleLinesSingle": "Single line",
    "settings.trackTitleLinesDouble": "Two lines",
    "settings.explicitBadge": "Explicit badge",
    "settings.explicitBadgeDescription": "Show or hide the explicit content badge in the player.",
    "settings.sizeSmaller": "Smaller",
    "settings.sizeSmall": "Small",
    "settings.sizeDefault": "Default",
    "settings.sizeBig": "Big",
    "settings.sizeBigger": "Bigger",
    "settings.newPlaylistsPublic": "New playlists are public by default",
    "settings.privateSession": "Start a private session",
    "settings.shareListening": "Share listening activity with followers",
    "settings.showFollowers": "Show followers and following",
    "settings.connectedApps": "Connected apps",
    "settings.connectedAppsDescription": "Manage third-party apps with access to listening data.",
    "settings.discordConnect": "Connect Discord",
    "settings.discordConnectDescription": "Use Knobb Desktop on the same machine as Discord to publish Rich Presence.",
    "settings.discordConnectDialogTitle": "Connect Discord",
    "settings.discordConnectDialogDescription": "Knobb Desktop can publish Discord activity directly on the same machine as Discord. The browser build cannot publish Discord Rich Presence on its own.",
    "settings.discordPresence": "Discord activity status",
    "settings.discordPresenceDescription": "Let Knobb Desktop publish your current track to Discord Rich Presence while you listen.",
    "settings.discordBridge": "Knobb Desktop",
    "settings.discordBridgeConnected": "Knobb Desktop is running and can publish Discord activity from this device.",
    "settings.discordBridgeMissing": "Discord activity requires Knobb Desktop. The website alone cannot publish Rich Presence.",
    "settings.discordBridgeSetupRequired": "Knobb Desktop is running, but it still needs a Discord application client ID in discord-presence.bridge.json.",
    "settings.discordAppConnected": "Discord desktop is connected. Rich Presence can update while you listen.",
    "settings.discordAppWaiting": "Knobb Desktop is ready, but Discord desktop is not connected yet. Open the Discord desktop app on this machine.",
    "settings.discordBridgeStatusConnected": "Discord connected",
    "settings.discordBridgeStatusOffline": "Desktop required",
    "settings.discordBridgeStatusSetupRequired": "Setup required",
    "settings.discordBridgeStatusWaiting": "Open Discord desktop",
    "settings.discordBridgeReady": "Desktop ready",
    "settings.discordBridgeWaiting": "Waiting for desktop",
    "settings.discordConfig": "Config",
    "settings.discordConfigFile": "Config file",
    "settings.discordDesktop": "Desktop app",
    "settings.discordConfigStepTitle": "1. Add your Discord app client ID",
    "settings.discordConfigStepDescription": "Knobb Desktop reads discord-presence.bridge.json from its desktop config folder. Copy the template below, set your Discord application client ID, and save the file there.",
    "settings.discordConfigDesktopStepDescription": "Copy the template below, set your Discord application client ID, and save it as discord-presence.bridge.json inside {{path}}.",
    "settings.discordCompanionStepTitle": "2. Start Knobb Desktop",
    "settings.discordCompanionStepDescription": "Run Knobb Desktop on the same machine as Discord so it can publish Rich Presence directly.",
    "settings.discordAlternativeCommand": "Terminal fallback",
    "settings.discordDesktopStepTitle": "3. Open Discord desktop",
    "settings.discordDesktopStepDescription": "Open the Discord desktop app, then refresh this panel. Once all three checks are ready, enable activity status.",
    "settings.copyConfigTemplate": "Copy config template",
    "settings.copyConfigPath": "Copy config path",
    "settings.openConfigFolder": "Open config folder",
    "settings.revealConfigFile": "Reveal config file",
    "settings.copyCompanionCommand": "Copy desktop command",
    "settings.discordDesktopAppRunning": "Knobb Desktop is already handling Discord presence on this device.",
    "settings.refreshStatus": "Refresh status",
    "settings.enableDiscordPresence": "Enable activity status",
    "settings.discordPresenceEnabled": "Activity status enabled",
    "settings.discordPresenceEnabledToast": "Discord activity status enabled",
    "settings.discordConfigTemplateCopied": "Discord config template copied",
    "settings.discordConfigPathCopied": "Discord config path copied",
    "settings.discordCommandCopied": "Discord desktop command copied",
    "settings.discordStatusRefreshFailed": "Failed to refresh Discord status",
    "settings.copyFailed": "Clipboard copy failed",
    "settings.openSetup": "Open setup",
    "settings.listenBrainz": "ListenBrainz scrobbling",
    "settings.listenBrainzDescription": "Submit now-playing updates and completed listens from Knobb to your ListenBrainz account.",
    "settings.listenBrainzToken": "ListenBrainz token",
    "settings.listenBrainzTokenPlaceholder": "Paste your ListenBrainz user token",
    "settings.testConnection": "Test connection",
    "settings.connectedAs": "Connected as {{name}}",
    "settings.lastfm": "Last.fm scrobbling",
    "settings.lastfmDescription": "Needs a signed server proxy for write access, so it is not active in this browser-only build yet.",
    "settings.view": "View",
    "settings.equalizer": "Equalizer",
    "settings.presets": "Presets",
    "settings.flat": "Flat",
    "settings.bassBooster": "Bass Booster",
    "settings.bassReducer": "Bass Reducer",
    "settings.vocalBooster": "Vocal Booster",
    "settings.trebleBooster": "Treble Booster",
    "settings.loudness": "Loudness",
    "settings.rock": "Rock",
    "settings.electronic": "Electronic",
    "settings.custom": "Custom",
    "settings.preamp": "Preamp",
    "settings.reset": "Reset",
    "settings.downloadsEntries": "Downloads: {{count}} entries",
    "settings.offlineContent": "Content marked for offline use",
    "settings.cacheSize": "Cache: {{size}} MB",
    "settings.cacheDescription": "Temporary files for faster loading",
    "settings.clearCache": "Clear cache",
    "settings.offlineStorageLocation": "Offline storage location",
    "settings.presetApplied": "{{preset}} preset applied",
    "settings.equalizerReset": "Equalizer reset",
    "settings.cacheCleared": "Cache cleared",
  },
  bn: {
    "nav.home": "হোম",
    "nav.search": "খুঁজুন",
    "nav.browse": "ব্রাউজ",
    "nav.unreleased": "আনরিলিজড",
    "nav.library": "লাইব্রেরি",
    "nav.profile": "প্রোফাইল",
    "nav.notifications": "নোটিফিকেশন",
    "nav.history": "হিস্ট্রি",
    "nav.settings": "সেটিংস",

    "sidebar.searchPlaceholder": "খুঁজুন...",
    "sidebar.searchLibraryPlaceholder": "লাইব্রেরিতে খুঁজুন...",
    "sidebar.loadingSearch": "সার্চ লোড হচ্ছে...",
    "sidebar.yourLibrary": "আপনার লাইব্রেরি",
    "sidebar.playlists": "প্লেলিস্ট",
    "sidebar.albums": "অ্যালবাম",
    "sidebar.artists": "শিল্পী",
    "sidebar.recents": "সাম্প্রতিক",
    "sidebar.alphabetical": "বর্ণানুক্রমিক",
    "sidebar.noMatchesFound": "কোনো মিল পাওয়া যায়নি",
    "sidebar.createPlaylist": "তৈরি করুন",
    "sidebar.newPlaylist": "নতুন প্লেলিস্ট",
    "sidebar.playlistNamePlaceholder": "প্লেলিস্টের নাম",
    "sidebar.playlistCreated": "\"{{name}}\" তৈরি হয়েছে",
    "sidebar.playlistCreateFailed": "প্লেলিস্ট তৈরি করা যায়নি",
    "sidebar.deletePlaylistConfirm": "\"{{name}}\" মুছে ফেলবেন? এটি আর ফেরানো যাবে না।",
    "sidebar.playlistDeleted": "প্লেলিস্ট মুছে ফেলা হয়েছে",
    "sidebar.likedSongs": "পছন্দের গান",
    "sidebar.localFiles": "লোকাল ফাইল",
    "sidebar.localFilesMeta": "এই ডিভাইসে · {{count}}টি ট্র্যাক",
    "sidebar.playlistMeta": "প্লেলিস্ট · {{count}}টি গান",
    "sidebar.artist": "শিল্পী",

    "settings.title": "সেটিংস",
    "settings.searchAria": "সেটিংস খুঁজুন",
    "settings.searchPlaceholder": "সেটিংস খুঁজুন",
    "settings.searchNoResults": "আপনার খোঁজার সাথে মিল থাকা কোনো সেটিংস পাওয়া যায়নি।",
    "settings.account": "অ্যাকাউন্ট",
    "settings.language": "ভাষা",
    "settings.audioQuality": "অডিও কোয়ালিটি",
    "settings.yourLibrary": "আপনার লাইব্রেরি",
    "settings.display": "ডিসপ্লে",
    "settings.social": "সোশ্যাল",
    "settings.playback": "প্লেব্যাক",
    "settings.storage": "স্টোরেজ",
    "settings.guest": "গেস্ট",
    "settings.connectedAccount": "সংযুক্ত অ্যাকাউন্ট",
    "settings.signInManage": "অ্যাকাউন্ট সেটিংস ব্যবস্থাপনা করতে সাইন ইন করুন",
    "settings.edit": "এডিট",
    "settings.signIn": "সাইন ইন",
    "settings.signOut": "সাইন আউট",
    "settings.signOutDescription": "এই ডিভাইসে সেশন শেষ করুন",
    "settings.chooseLanguage": "ভাষা নির্বাচন করুন",
    "settings.languageDescription": "অ্যাপের মূল ইন্টারফেসে পরিবর্তন সঙ্গে সঙ্গে দেখা যাবে।",
    "settings.languageEnglish": "ইংরেজি",
    "settings.languageBangla": "বাংলা",
    "settings.streamingQuality": "স্ট্রিমিং কোয়ালিটি",
    "settings.downloadFormat": "ডাউনলোড ফরম্যাট",
    "settings.autoAdjustQuality": "অটো-অ্যাডজাস্ট কোয়ালিটি",
    "settings.recommendedOn": "প্রস্তাবিত: অন",
    "settings.equalizerDescription": "প্লেব্যাক EQ চালু করুন। Reset দিলে বর্তমান EQ curve মুছে যাবে।",
    "settings.preservePitch": "পিচ সংরক্ষণ",
    "settings.preservePitchDescription": "প্লেব্যাক স্পিড বদলালেও ভোকালের আসল পিচ ধরে রাখুন।",
    "settings.volumeNormalization": "ভলিউম নরমালাইজেশন",
    "settings.volumeNormalizationDescription": "আরও সমান প্লেব্যাক লেভেলের জন্য ট্র্যাকের ভলিউম নরমালাইজ করুন।",
    "settings.compactLibrary": "কমপ্যাক্ট লাইব্রেরি লেআউট ব্যবহার করুন",
    "settings.showLocalFiles": "লোকাল ফাইল দেখান",
    "settings.showLocalFilesDescription": "লাইব্রেরি সাইডবার আর কালেকশন পেজে ইমপোর্ট করা যায় এমন লোকাল ফাইল সেকশন চালু রাখুন।",
    "settings.openLocalFiles": "লোকাল ফাইল খুলুন",
    "settings.localFilesCount": "লোকাল ফাইল: {{count}}",
    "settings.localFilesStorage": "লোকালি সংরক্ষিত: {{size}}",
    "settings.offlineApp": "অফলাইন অ্যাপ শেল",
    "settings.offlineAppReady": "মূল পেজগুলো এই ডিভাইসে অফলাইনে চালুর জন্য ক্যাশ করা আছে।",
    "settings.offlineAppPending": "এই ডিভাইসের জন্য অফলাইন ক্যাশিং এখনও প্রস্তুত হচ্ছে।",
    "settings.desktopAppDescription": "এই ডিভাইসে Knobb Desktop নেটিভভাবে চলছে, তাই এটি browser offline shell-এর উপর নির্ভর করে না।",
    "settings.installApp": "অ্যাপ ইনস্টল করুন",
    "settings.installAppDescription": "আরও নেটিভ অ্যাপের মতো অভিজ্ঞতার জন্য Knobb-কে হোম স্ক্রিন বা ডেস্কটপে যোগ করুন।",
    "settings.installAppDesktopDescription": "এই ডিভাইসে Knobb Desktop ইতিমধ্যে ইনস্টল করা ও চালু আছে।",
    "settings.installNow": "ইনস্টল",
    "settings.installed": "ইনস্টল হয়েছে",
    "settings.notAvailable": "উপলব্ধ নয়",
    "settings.desktopDownloads": "ডেস্কটপ ডাউনলোড",
    "settings.desktopDownloadsDescription": "Windows release-গুলো desktop repo থেকে প্রকাশিত হয় এবং tagged GitHub release থেকে auto-update নেয়। Signed macOS publishing আপাতত Apple Developer enrollment না হওয়া পর্যন্ত বন্ধ আছে।",
    "settings.desktopMainApp": "Knobb Desktop",
    "settings.desktopMainAppDescription": "ট্রে সাপোর্ট আর native Discord presence-সহ পূর্ণ desktop app। Windows release live আছে; Apple signing না থাকা পর্যন্ত macOS packaging শুধু local-only।",
    "settings.desktopCompanionApp": "Knobb Discord Companion",
    "settings.desktopCompanionDescription": "হালকা bridge-only helper। Windows installer latest release page-এ আছে; signed macOS publishing আপাতত বন্ধ আছে।",
    "settings.desktopDownloadMac": "macOS-এর জন্য ডাউনলোড",
    "settings.desktopDownloadWindows": "Windows-এর জন্য ডাউনলোড",
    "settings.desktopViewRelease": "সর্বশেষ রিলিজ দেখুন",
    "settings.desktopViewRepo": "ডেস্কটপ repo খুলুন",
    "settings.desktopUpdateVersion": "বর্তমান ভার্সন: {{version}}",
    "settings.desktopUpdatePlatform": "প্ল্যাটফর্ম: {{platform}}",
    "settings.desktopCheckUpdates": "আপডেট দেখুন",
    "settings.desktopRetryUpdate": "আবার আপডেট চেক করুন",
    "settings.desktopRestartUpdate": "আপডেট দিতে রিস্টার্ট করুন",
    "settings.dynamicCards": "ডাইনামিক কার্ডস",
    "settings.dynamicCardsDescription": "মিডিয়া কার্ডের হোভার লিফট, জুম এবং ফ্লোটিং অ্যাকশন বাটন নিয়ন্ত্রণ করে।",
    "settings.dynamicCardsEnabledOption": "ডাইনামিক",
    "settings.dynamicCardsDisabledOption": "সাধারণ",
    "settings.libraryCardStyle": "লাইব্রেরি আইটেম স্টাইল",
    "settings.libraryCardStyleDescription": "আর্টওয়ার্ক কার্ড আর কমপ্যাক্ট লিস্ট লেআউটের মধ্যে বদলান।",
    "settings.libraryCardStyleCover": "কভার",
    "settings.libraryCardStyleList": "লিস্ট",
    "settings.rightPanelStyle": "ডান সাইডবার স্টাইল",
    "settings.rightPanelStyleDescription": "সাধারণ ক্লাসিক প্যানেল আর আর্টওয়ার্ক-ভিত্তিক ব্লার সংস্করণের মধ্যে বেছে নিন।",
    "settings.rightPanelStyleClassic": "ক্লাসিক",
    "settings.rightPanelStyleArtwork": "আর্টওয়ার্ক ব্লার",
    "settings.bottomPlayerStyle": "নিচের প্লেয়ার স্টাইল",
    "settings.bottomPlayerStyleDescription": "বর্তমান টিন্টেড প্লেয়ার বার আর কালো সংস্করণের মধ্যে বেছে নিন।",
    "settings.bottomPlayerStyleCurrent": "বর্তমান",
    "settings.bottomPlayerStyleBlack": "কালো",
    "settings.sidebarStyle": "সাইডবার স্টাইল",
    "settings.sidebarStyleDescription": "লাইব্রেরি সাইডবারকে সহজ ক্লাসিক বা আরও আবহময় আর্টওয়ার্ক-অনুপ্রাণিত শেলে বদলান।",
    "settings.sidebarStyleClassic": "ক্লাসিক",
    "settings.sidebarStyleArtwork": "আর্টওয়ার্ক ব্লার",
    "settings.cardSize": "কার্ড সাইজ",
    "settings.cardSizeDescription": "ছোট কার্ডে প্রতি সারিতে আরও বেশি আইটেম দেখাবে।",
    "settings.websiteMode": "ওয়েবসাইট মোড",
    "settings.websiteModeDescription": "বর্তমান ধারালো লেআউট আর নরম, আরও ফ্লুইড রাউন্ডিশ লুকের মধ্যে বদলান।",
    "settings.websiteModeEdgy": "এজি",
    "settings.websiteModeRoundish": "রাউন্ডিশ",
    "settings.pageDensity": "পেজ ঘনত্ব",
    "settings.pageDensityDescription": "ইন্টারফেসে কতটা ঘনভাবে স্পেসিং ও রো সাজানো হবে তা বেছে নিন।",
    "settings.pageDensityComfortable": "স্বস্তিদায়ক",
    "settings.pageDensityCompact": "কমপ্যাক্ট",
    "settings.font": "ফন্ট",
    "settings.fontDescription": "ডিফল্ট হিসেবে Outfit রাখুন, অথবা পুরো ইন্টারফেসে Space Grotesk ব্যবহার করুন।",
    "settings.fontDefault": "ডিফল্ট (Outfit)",
    "settings.fontGrotesk": "Space Grotesk",
    "settings.showSidebar": "সাইডবার দেখান",
    "settings.showSidebarDescription": "ডেস্কটপে নেভিগেশন ও লাইব্রেরির জন্য সাইডবার দৃশ্যমান রাখুন।",
    "settings.showScrollbar": "স্ক্রলবার দেখান",
    "settings.showScrollbarDescription": "মাউস দিয়ে নেভিগেশনের জন্য অ্যাপের প্যানেল ও সাইডবারে ড্র্যাগ করা যায় এমন দৃশ্যমান স্ক্রলবার দেখান।",
    "settings.optionYes": "হ্যাঁ",
    "settings.optionNo": "না",
    "settings.optionShow": "দেখান",
    "settings.optionHide": "লুকান",
    "settings.libraryOpenState": "লাইব্রেরি খোলার অবস্থা",
    "settings.libraryOpenStateDescription": "ডেস্কটপ লাইব্রেরি সাইডবার শুরুতে খোলা থাকবে নাকি ভাঁজ করা থাকবে তা বেছে নিন।",
    "settings.libraryOpenStateExpanded": "খোলা",
    "settings.libraryOpenStateCollapsed": "ভাঁজ করা",
    "settings.librarySortDefault": "লাইব্রেরি ডিফল্ট সাজানো",
    "settings.librarySortDefaultDescription": "লাইব্রেরি খুললে কোন ক্রমে আইটেম দেখাবে তা বেছে নিন।",
    "settings.librarySortRecents": "সাম্প্রতিক",
    "settings.librarySortAlphabetical": "বর্ণানুক্রমিক",
    "settings.coverArtCorners": "কভার আর্ট কর্নার",
    "settings.coverArtCornersDescription": "অ্যাপজুড়ে কভার আর্ট ধারালো কোণা নাকি গোলাকার হবে তা বেছে নিন।",
    "settings.coverArtCornersSharp": "ধারালো",
    "settings.coverArtCornersRounded": "গোলাকার",
    "settings.accentSource": "অ্যাকসেন্ট উৎস",
    "settings.accentSourceDescription": "চলমান ট্র্যাকের আর্টওয়ার্ক থেকে অ্যাকসেন্ট নিন, অথবা পুরো অ্যাপে নিরপেক্ষ থিম অ্যাকসেন্ট রাখুন।",
    "settings.accentSourceDynamic": "ডাইনামিক",
    "settings.accentSourceTheme": "থিম",
    "settings.animationMode": "অ্যানিমেশন",
    "settings.animationModeDescription": "পূর্ণ অ্যানিমেশন, কম অ্যানিমেশন, বা একেবারে বন্ধ করার মধ্যে বেছে নিন।",
    "settings.animationModeFull": "পূর্ণ",
    "settings.animationModeReduced": "কম",
    "settings.animationModeOff": "বন্ধ",
    "settings.blurEffects": "ব্লার ইফেক্ট",
    "settings.blurEffectsDescription": "প্যানেলে ব্যবহৃত ফ্রস্টেড গ্লাস ও ব্যাকগ্রাউন্ড ব্লার ইফেক্ট চালু বা বন্ধ করুন।",
    "settings.rightPanelDefaultTab": "ডান প্যানেলের ডিফল্ট ট্যাব",
    "settings.rightPanelDefaultTabDescription": "ডান প্যানেল স্বয়ংক্রিয়ভাবে খুললে কোন ট্যাব পছন্দ করবে তা ঠিক করুন।",
    "settings.rightPanelTabQueue": "কিউ",
    "settings.rightPanelTabLyrics": "লিরিক্স",
    "settings.rightPanelAutoOpen": "ডান প্যানেল স্বয়ংক্রিয় খোলা",
    "settings.rightPanelAutoOpenDescription": "প্লেব্যাক শুরু হলে ডান প্যানেল স্বয়ংক্রিয়ভাবে খুলবে কি না তা নির্ধারণ করুন।",
    "settings.rightPanelAutoOpenAlways": "সবসময়",
    "settings.rightPanelAutoOpenWhilePlaying": "শুধু প্লে হলে",
    "settings.rightPanelAutoOpenNever": "কখনো না",
    "settings.lyricsSyncMode": "লিরিক্স সিঙ্ক মোড",
    "settings.lyricsSyncModeDescription": "লিরিক্সকে প্লেব্যাকের সাথে অনুসরণ করান বা স্থির ভিউতে রাখুন।",
    "settings.lyricsSyncModeFollow": "প্লেব্যাক অনুসরণ",
    "settings.lyricsSyncModeStatic": "স্থির",
    "settings.playerButtonsLayout": "প্লেয়ার বাটন লেআউট",
    "settings.playerButtonsLayoutDescription": "নিচের প্লেয়ারের কন্ট্রোলগুলো ঘন বা একটু বেশি ফাঁকা স্পেসিংয়ে দেখান।",
    "settings.playerButtonsLayoutCompact": "কমপ্যাক্ট",
    "settings.playerButtonsLayoutSpacious": "ফাঁকা",
    "settings.trackTitleLines": "ট্র্যাক শিরোনামের লাইন",
    "settings.trackTitleLinesDescription": "প্লেয়ারে শিরোনাম এক লাইনে থাকবে নাকি দুই লাইনে মোড়াতে পারবে তা বেছে নিন।",
    "settings.trackTitleLinesSingle": "এক লাইন",
    "settings.trackTitleLinesDouble": "দুই লাইন",
    "settings.explicitBadge": "এক্সপ্লিসিট ব্যাজ",
    "settings.explicitBadgeDescription": "প্লেয়ারে explicit কনটেন্ট ব্যাজ দেখাবেন কি না ঠিক করুন।",
    "settings.sizeSmaller": "সবচেয়ে ছোট",
    "settings.sizeSmall": "ছোট",
    "settings.sizeDefault": "ডিফল্ট",
    "settings.sizeBig": "বড়",
    "settings.sizeBigger": "সবচেয়ে বড়",
    "settings.newPlaylistsPublic": "নতুন প্লেলিস্ট ডিফল্টভাবে পাবলিক থাকবে",
    "settings.privateSession": "প্রাইভেট সেশন শুরু করুন",
    "settings.shareListening": "ফলোয়ারদের সাথে লিসনিং অ্যাক্টিভিটি শেয়ার করুন",
    "settings.showFollowers": "ফলোয়ার ও ফলোয়িং দেখান",
    "settings.connectedApps": "সংযুক্ত অ্যাপস",
    "settings.connectedAppsDescription": "লিসনিং ডেটায় যেসব থার্ড-পার্টি অ্যাপের অ্যাক্সেস আছে সেগুলো পরিচালনা করুন।",
    "settings.discordConnect": "Discord সংযুক্ত করুন",
    "settings.discordConnectDescription": "Discord-এর একই ডিভাইসে Knobb Desktop ব্যবহার করে Rich Presence পাঠান।",
    "settings.discordConnectDialogTitle": "Discord সংযুক্ত করুন",
    "settings.discordConnectDialogDescription": "Discord-এর একই ডিভাইসে Knobb Desktop চললে Knobb সরাসরি activity পাঠাতে পারে। browser build একা Discord Rich Presence পাঠাতে পারে না।",
    "settings.discordPresence": "Discord অ্যাক্টিভিটি স্ট্যাটাস",
    "settings.discordPresenceDescription": "Knobb Desktop-এ শোনার সময় আপনার বর্তমান ট্র্যাক Discord Rich Presence-এ পাঠাতে দিন।",
    "settings.discordBridge": "Knobb Desktop",
    "settings.discordBridgeConnected": "এই ডিভাইসে Knobb Desktop চালু আছে এবং Discord activity পাঠাতে পারবে।",
    "settings.discordBridgeMissing": "Discord অ্যাক্টিভিটির জন্য Knobb Desktop দরকার। শুধু website থেকে Rich Presence পাঠানো যাবে না।",
    "settings.discordBridgeSetupRequired": "Knobb Desktop চালু আছে, কিন্তু `discord-presence.bridge.json`-এ এখনও Discord application client ID দিতে হবে।",
    "settings.discordAppConnected": "Discord desktop যুক্ত আছে। এখন আপনি শুনলে Rich Presence আপডেট হতে পারবে।",
    "settings.discordAppWaiting": "Knobb Desktop প্রস্তুত, কিন্তু Discord desktop এখনও যুক্ত হয়নি। এই ডিভাইসে Discord desktop app খুলুন।",
    "settings.discordBridgeStatusConnected": "Discord যুক্ত",
    "settings.discordBridgeStatusOffline": "Desktop দরকার",
    "settings.discordBridgeStatusSetupRequired": "সেটআপ বাকি",
    "settings.discordBridgeStatusWaiting": "Discord desktop খুলুন",
    "settings.discordBridgeReady": "Desktop প্রস্তুত",
    "settings.discordBridgeWaiting": "Desktop-এর জন্য অপেক্ষা করছে",
    "settings.discordConfig": "কনফিগ",
    "settings.discordConfigFile": "কনফিগ ফাইল",
    "settings.discordDesktop": "ডেস্কটপ অ্যাপ",
    "settings.discordConfigStepTitle": "1. Discord app client ID দিন",
    "settings.discordConfigStepDescription": "Knobb Desktop তার config folder থেকে discord-presence.bridge.json পড়ে। নিচের টেমপ্লেট কপি করুন, Discord application client ID বসান, তারপর ফাইলটি সেখানে সেভ করুন।",
    "settings.discordConfigDesktopStepDescription": "নিচের টেমপ্লেট কপি করুন, আপনার Discord application client ID বসান, তারপর {{path}}-এর ভিতরে `discord-presence.bridge.json` নামে সেভ করুন।",
    "settings.discordCompanionStepTitle": "2. Knobb Desktop চালু করুন",
    "settings.discordCompanionStepDescription": "Discord-এর একই ডিভাইসে নেটিভ Rich Presence-এর জন্য Knobb Desktop চালান।",
    "settings.discordAlternativeCommand": "টার্মিনাল বিকল্প",
    "settings.discordDesktopStepTitle": "3. Discord desktop খুলুন",
    "settings.discordDesktopStepDescription": "Discord desktop app খুলে এই প্যানেল রিফ্রেশ করুন। তিনটি চেক প্রস্তুত হলে activity status অন করুন।",
    "settings.copyConfigTemplate": "কনফিগ টেমপ্লেট কপি করুন",
    "settings.copyConfigPath": "কনফিগ পাথ কপি করুন",
    "settings.openConfigFolder": "কনফিগ ফোল্ডার খুলুন",
    "settings.revealConfigFile": "কনফিগ ফাইল দেখান",
    "settings.copyCompanionCommand": "Desktop কমান্ড কপি করুন",
    "settings.discordDesktopAppRunning": "এই ডিভাইসে Knobb Desktop ইতিমধ্যে Discord presence পরিচালনা করছে।",
    "settings.refreshStatus": "স্ট্যাটাস রিফ্রেশ করুন",
    "settings.enableDiscordPresence": "অ্যাক্টিভিটি স্ট্যাটাস অন করুন",
    "settings.discordPresenceEnabled": "অ্যাক্টিভিটি স্ট্যাটাস চালু",
    "settings.discordPresenceEnabledToast": "Discord অ্যাক্টিভিটি স্ট্যাটাস চালু হয়েছে",
    "settings.discordConfigTemplateCopied": "Discord কনফিগ টেমপ্লেট কপি হয়েছে",
    "settings.discordConfigPathCopied": "Discord কনফিগ পাথ কপি হয়েছে",
    "settings.discordCommandCopied": "Discord desktop কমান্ড কপি হয়েছে",
    "settings.discordStatusRefreshFailed": "Discord স্ট্যাটাস রিফ্রেশ করা যায়নি",
    "settings.copyFailed": "ক্লিপবোর্ডে কপি করা যায়নি",
    "settings.openSetup": "সেটআপ খুলুন",
    "settings.listenBrainz": "ListenBrainz স্ক্রবলিং",
    "settings.listenBrainzDescription": "Knobb থেকে আপনার ListenBrainz অ্যাকাউন্টে now playing আপডেট আর সম্পূর্ণ listen পাঠান।",
    "settings.listenBrainzToken": "ListenBrainz টোকেন",
    "settings.listenBrainzTokenPlaceholder": "আপনার ListenBrainz user token পেস্ট করুন",
    "settings.testConnection": "সংযোগ পরীক্ষা করুন",
    "settings.connectedAs": "{{name}} হিসেবে সংযুক্ত",
    "settings.lastfm": "Last.fm স্ক্রবলিং",
    "settings.lastfmDescription": "রাইট অ্যাক্সেসের জন্য signed server proxy লাগে, তাই এই browser-only build-এ এটি এখনও চালু নয়।",
    "settings.view": "দেখুন",
    "settings.equalizer": "ইকুয়ালাইজার",
    "settings.presets": "প্রিসেট",
    "settings.flat": "ফ্ল্যাট",
    "settings.bassBooster": "বেস বুস্টার",
    "settings.bassReducer": "বেস রিডিউসার",
    "settings.vocalBooster": "ভোকাল বুস্টার",
    "settings.trebleBooster": "ট্রেবল বুস্টার",
    "settings.loudness": "লাউডনেস",
    "settings.rock": "রক",
    "settings.electronic": "ইলেকট্রনিক",
    "settings.custom": "কাস্টম",
    "settings.preamp": "প্রিঅ্যাম্প",
    "settings.reset": "রিসেট",
    "settings.downloadsEntries": "ডাউনলোড: {{count}}টি এন্ট্রি",
    "settings.offlineContent": "অফলাইন ব্যবহারের জন্য চিহ্নিত কনটেন্ট",
    "settings.cacheSize": "ক্যাশ: {{size}} MB",
    "settings.cacheDescription": "দ্রুত লোডের জন্য অস্থায়ী ফাইল",
    "settings.clearCache": "ক্যাশ পরিষ্কার করুন",
    "settings.offlineStorageLocation": "অফলাইন স্টোরেজ লোকেশন",
    "settings.presetApplied": "{{preset}} প্রিসেট প্রয়োগ করা হয়েছে",
    "settings.equalizerReset": "ইকুয়ালাইজার রিসেট হয়েছে",
    "settings.cacheCleared": "ক্যাশ পরিষ্কার করা হয়েছে",
  },
} as const;

function resolveInitialLanguage(): AppLanguage {
  const storedLanguage = safeStorageGetItem(LANGUAGE_STORAGE_KEY);
  return storedLanguage === "bn" ? "bn" : "en";
}

function interpolate(template: string, values?: TranslationValues) {
  if (!values) return template;
  return Object.entries(values).reduce(
    (message, [key, value]) => message.replaceAll(`{{${key}}}`, String(value)),
    template,
  );
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const auth = useOptionalAuth();
  const user = auth?.user ?? null;
  const [language, setLanguageState] = useState<AppLanguage>(resolveInitialLanguage);
  const accountSyncReadyRef = useRef(false);
  const lastSyncedLanguageRef = useRef<AppLanguage | null>(null);
  const languageRef = useRef(language);
  languageRef.current = language;

  useEffect(() => {
    safeStorageSetItem(LANGUAGE_STORAGE_KEY, language);
    if (typeof document !== "undefined") {
      document.documentElement.lang = language;
    }
  }, [language]);

  useEffect(() => {
    if (!user) {
      accountSyncReadyRef.current = false;
      lastSyncedLanguageRef.current = null;
      return;
    }

    let cancelled = false;

    void (async () => {
      const { data, error } = await loadProfilePreferences(user.id);
      if (cancelled) return;
      if (error) {
        accountSyncReadyRef.current = true;
        return;
      }

      const remoteLanguage = data?.language_preference === "bn" ? "bn" : data?.language_preference === "en" ? "en" : null;
      if (remoteLanguage) {
        lastSyncedLanguageRef.current = remoteLanguage;
        setLanguageState(remoteLanguage);
        safeStorageSetItem(LANGUAGE_STORAGE_KEY, remoteLanguage);
      } else {
        lastSyncedLanguageRef.current = languageRef.current;
        await persistProfilePreferences(user.id, { language_preference: languageRef.current });
      }

      if (!cancelled) {
        accountSyncReadyRef.current = true;
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [user]);

  useEffect(() => {
    if (!user || !accountSyncReadyRef.current || lastSyncedLanguageRef.current === language) return;
    lastSyncedLanguageRef.current = language;
    void persistProfilePreferences(user.id, { language_preference: language });
  }, [language, user]);

  const value = useMemo<LanguageContextType>(() => ({
    language,
    setLanguage: setLanguageState,
    t: (key, values) => interpolate(translations[language][key] || translations.en[key], values),
  }), [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }

  return context;
}
