// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { safeSupabaseStorage } from "@/lib/safeStorage";

function requireSupabaseEnv(name: "VITE_SUPABASE_URL" | "VITE_SUPABASE_PUBLISHABLE_KEY", value: string | undefined) {
  if (value) return value;

  throw new Error(
    `Missing ${name}. Set ${name} in your deploy environment and rebuild the app.`,
  );
}

const SUPABASE_URL = requireSupabaseEnv("VITE_SUPABASE_URL", import.meta.env.VITE_SUPABASE_URL);
const SUPABASE_PUBLISHABLE_KEY = requireSupabaseEnv(
  "VITE_SUPABASE_PUBLISHABLE_KEY",
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,
);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeSupabaseStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
